apiVersion: v1
kind: Template
metadata:
  name: "quorum-pv-pvc"
message: "quorum-pv-pvc"
objects:

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: "nfs-pv-${PROJECTNAME}"
  spec:
    capacity:
      storage: 1Gi 
    accessModes:
      - ReadWriteMany 
    persistentVolumeReclaimPolicy: Retain 
    nfs: 
      path: "/nfs/share/${PROJECTNAME}"
      server: centos7-2-15 
      readOnly: false
   
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "sharestoragepvc"
  spec:
    accessModes:
    - "ReadWriteMany"
    resources:
      requests:
        storage: "100Mi"

parameters:
###################### quorum parameters ############################################
- name: PROJECTNAME
  displayName: project name
  description: project name 
  value: "test1"

