apiVersion: v1
kind: Template
metadata:
  name: "quorum-explorer"
message: "quorum-explorer"
objects:

- apiVersion: v1
  kind: Route
  metadata:
    name: explorer
  spec:
    host: "${URL}"
    path: "/" 
    to:
      kind: Service
      name: webapp-svc

- apiVersion: v1
  kind: Service
  metadata:
    name: "webapp-svc"
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: exporer-port
    selector:
      name: cbx-quorum-explorer

- apiVersion: v1
  kind: Service
  metadata:
    name: api-svc
    lables:
      name: api-svc
  spec:
    type: NodePort
    ports:
      - port: 28080
        nodePort: ${{API_PORT}}
        protocol: TCP
        targetPort: 8080
        name: api-svc
    selector:
        name: cbx-quorum-explorer

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "cbx-quorum-explorer"
  spec:
    replicas: 1
    selector:
      name: cbx-quorum-explorer
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: cbx-quorum-explorer
      spec:
        containers:
########################### webapp container #######################################
        - name: cbx-quorum-explorer-webapp
          securityContext:
            runAsUser: 0
          env:
          - name: API_URL
            value: "${{API_URL}}"
          image: reg.newnewchain.com/baas/quorum-explorer-webapp
          imagePullPolicy: Always
          ports: 
            - name: webapp-port
              containerPort: 80
########################### syncer container #######################################
        - name: cbx-quorum-explorer-http-api
          securityContext:
            runAsUser: 0
          image: reg.newnewchain.com/baas/quorum-explorer-http-api
          imagePullPolicy: Always
          ports: 
            - name: http-apiport
              containerPort: 8080
########################### http-api container #######################################
        - name: cbx-quorum-explorer-syncer
          securityContext:
            runAsUser: 0
          env:
          - name: QUORUM_HOST
            value: quorumrpc
          - name: QUORUM_PORT
            value: "22000"
          - name: MONGO_HOST
            value: "localhost"
          image: reg.newnewchain.com/baas/quorum-explorer-syncer
          imagePullPolicy: Always
          ports: 
            - name: explorer-port
              containerPort: 3000
########################## mongodb container #######################################
        - name: mongodb
          securityContext:
            runAsUser: 0
          image: reg.newnewchain.com/baas/mongo:4.0-xenial
          imagePullPolicy: Always
          #command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          command: ["mongod", "--smallfiles", "--bind_ip", "0.0.0.0"]
          ports:
            - name: mongo-port
              containerPort: 27017
              protocol: TCP
      triggers:
      - type: ConfigChange
parameters:
- name: API_URL
  displayName: Explorer's API Server
  description: Explorer's API Server
  value: "http://baas-env-pre-public:32000"
- name: API_PORT
  displayName: Explorer's API PORT
  description: Explorer's API PORT
  value: "32000"
- name: URL
  displayName: Explorer's API PORT
  description: Explorer's API PORT
  value: "www.explorer.com"

